### ISSUE TITLE
Using .get() inside a React @observer render function throws an error

### ISSUE THREAD

**Issue by geekflyer** [danielearwicker/computed-async-mobx#12]
Hi @danielearwicker ,

when I use .get() inside the render() function of an @observer I get an error `×
Error: promisedComputed must be used inside reactions`. I thought the render function of a React component is also considered an reaction or am I wrong? 

Here's a small example

```tsx
@observer
class ConnectorTable extends React.Component<Props> {
  render() {
    const { connectorsStore } = this.props;

    const connectors = connectorsStore.connectors.get();

    if (!connectors) {
      return (
        <Loader active size="huge">
          Loading Connectors please wait...
        </Loader>
      );
    }

    return (
      <Page title="Connectors">
        <Item.Group>{connectors.map(renderConnector)}</Item.Group>
      </Page>
    );
  }
}
```

```ts
export class ConnectorsStore {

  constructor(private _orgStore = orgStore) {}

  connectors = promisedComputed(null, async () => {
    return fetchConnectors(this._orgStore.selectedOrgId);
  });
}
```

When I use `.value` it works as expected (because .value doesn't do the reaction check), but because .value is private typescript complains about it's usage.

**Comment by danielearwicker** [comment]
Oh dear. Give 3.1.0 a try - thanks for using the new API!

**Comment by atljoseph** [comment]
THIS IS STILL AN ISSUE.

Annoying because the whole reason i use mobx is to keep from having to use STATE.

Using:
    "computed-async-mobx": "^3.2.0",
    "react-native": "0.49.5",

**Comment by Kielan** [comment]
any update on this issue?

**Comment by Kielan** [comment]
@danielearwicker any feedback on this one? Is there a way to remove mobx as a dependency so that version 4 mobx doesn't throw an error for mutliple versions?

**Comment by danielearwicker** [comment]
There is a test in the repo `computed-async-mobx/interactive-tests/index.html` of a "slow calculator". Can you modify it until it replicates the issue, and then share it with me? Thanks.

(It already accesses the value from the `render` of an observer component, so I assumed the original problem reported here was fixed.)

**Comment by danielearwicker** [comment]
I guess the remaining issue was clashing versions. The latest version of this package has all mobx dependencies as peers, so you have to explicitly add your own dependencies on `mobx` and `mobx-utils`.

It works with current stable mobx releases, and also works with this combo:

- `mobx@4.0.0-beta.2`
- `mobx-utils@4.0.0-beta.2`
- `mobx-react@5.0.0-beta.2`

**Comment by norama** [comment]
I have this problem with everything latest:

- "computed-async-mobx": "^4.2.1",
- "mobx": "^6.0.1",
- "mobx-react": "^7.0.0",
- "mobx-utils": "^6.0.1",

Please solve this, I don't want to downgrade to beta...

**Comment by norama** [comment]
Also tried to downgrade to mobx mobx-react 5 versions but did not help...

**Comment by Ahmed-osama** [comment]
I have the same issue 
```
 "computed-async-mobx": "^4.1.1",
    "mobx": "^5.13.0",
    "mobx-utils": "^5.4.1"
```
as mentioned in another solution
