### ISSUE TITLE
Provide incorrect and correct examples for Gotchas section in README

### ISSUE THREAD

**Issue by stereokai** [danielearwicker/computed-async-mobx#16]
In this section: https://github.com/danielearwicker/computed-async-mobx#gotchas

It would be significantly more helpful to provide a "do" and "don't do" examples. Please consider :)

**Comment by Kielan** [comment]
documentation with decorators would be nice as well, until then trying to tease this project apart.

**Comment by stereokai** [comment]
Thank you very much @danielearwicker!
