### ISSUE TITLE
doesn't work with mobx 4

### ISSUE THREAD

**Issue by Kielan** [danielearwicker/computed-async-mobx#17]
pretty self explanatory, this is a very important dependency and needs to be maintained, maybe under mobx-utils dependency

https://github.com/mobxjs/mobx/issues/1082

**Comment by danielearwicker** [comment]
Absolutely. I will fix this up at the weekend.

**Comment by danielearwicker** [comment]
Wow. It sure doesn't. Will need to put in a shim layer to allow the library to work with both 3.x and 4-beta.

**Comment by danielearwicker** [comment]
Seems okay now, try 4.0.1.
