### ISSUE TITLE
Delay seems to occur even when no recent invocation has happened

### ISSUE THREAD

**Issue by flexiblefactory** [danielearwicker/computed-async-mobx#21]
I thought the idea of throttling was to only delay long enough to prevent repeated re-evaluations within the delay period. ie delay should not happen unless there has been a re-evaluation in the last `delay` ms.. Or am I missing something?

**Comment by ianmstew** [comment]
I have the same thought...  @danielearwicker would you be open to a `{ leading: true }` option like lodash's debounce/throttle?  If you're open to a merge I could work on a PR.  This would work the same way as @flexiblefactory described, and similar to Lodash throttle:

> Note: If leading and trailing options are true, func is invoked on the trailing edge of the timeout only if the throttled function is invoked more than once during the wait timeout.

https://lodash.com/docs/4.17.10#throttle

**Comment by danielearwicker** [comment]
@ianmstew absolutely!

**Comment by danielearwicker** [comment]
Still open to a PR but will close this in the meantime...
