### ISSUE TITLE
Error: promisedComputed must be used inside reactions

### ISSUE THREAD

**Issue by lapidus** [danielearwicker/computed-async-mobx#27]
Running into a similar error as others (https://github.com/danielearwicker/computed-async-mobx/issues/19) but can't figure out why.
My store has a substore 'data' which is making use of asyncComputed:

 ```
//inside data store
 @computed get concepts() {
    return this.fetchedConcepts.get()
  }
  fetchedConcepts = asyncComputed([], 0, async () => {
      return await getConcepts({ dataset }) // a promise
  })
```

The store is then used by a component:

 ```
const store = useExplorerStore()

<MyComponent data={store} />
 ```

The store is working apart from the `store.data` properties which are using asyncComputed.
Any hints appreciated 🙏

**Comment by danielearwicker** [comment]
I've seen reports of this error when using a mix of versions. I don't see it in testing when I use the latest versions. Right now that's:

    "computed-async-mobx": "^4.1.1",
    "mobx": "^5.13.0",
    "mobx-react": "^6.1.3",
    "mobx-utils": "^5.4.1"

Hope this helps!

**Comment by Ahmed-osama** [comment]
this didn't work for, I still have the same issue
