### ISSUE TITLE
Installation failed because of .git repository

### ISSUE THREAD

**Issue by flogy** [danielearwicker/computed-async-mobx#29]
Hi there

Thanks for this library! Could not yet test it but looks promising.

I had an issue during the installation using NPM saying `Appears to be a git repo or submodule.`. After a quick search I found the problem was that there is a `.git` directory inside the module root. After removing it everything worked fine (`cd node_modules/computed-async-mobx && rm -rf .git`).

Just to let you and others know - will now give the library a try 🙂 

Cheers

**Comment by danielearwicker** [comment]
Interesting, I never see an error about that with `npm` (using latest 6.11.2).

But it definitely doesn't make sense to include the `.git` folder in the package! So have published `computed-async-mobx@4.2.1` that removes it. Thanks for the heads-up.
