### ISSUE TITLE
Throttling observable

### ISSUE THREAD

**Issue by lishine** [danielearwicker/computed-async-mobx#31]
```
@observable values
throttledValues = throttledComputed(() => {
  return this.values
}, 2000)
```
When changing values, throttledValues changes immediately. This function is actually run only in the beginning. Is it the intended behavior ?
If so, how my intention can still be implemented?

**Comment by danielearwicker** [comment]
[Here is a simple demo](https://codesandbox.io/s/spring-mountain-6oj7m) with a counter.

Note: the value is read from an observer/reaction context, like you would with any observable/computed data in mobx. In this case using the `Observer` element.

When the value changes you can see the 2 second delay before the throttledValue catches up with it.

The execution to get the initial value is immediate, to avoid the first page load being unnecessarily slowed down.

**Comment by lishine** [comment]
I see.
I am trying to find out why it does not work for me.

**Comment by danielearwicker** [comment]
Try modifying the example to more closely resemble your code until it breaks?

**Comment by lishine** [comment]
So stupid me, values is an object. Of course, when returning values, it throttles only values and not values' properties or sub-properties.
In this case debounce is more suitable. So I ended debouncing the setValue.
```
	@observable values: Values
	@observable debouncedValues: Values
	@action setDebouncedValue = debounce((path: string, value: any) => {
		set(this.debouncedValues, path, value)
	}, 1500)
	@action setValue = (path: string) => (value: any) => {
		set(this.values, path, value)
		this.setDebouncedValue(path, value)
	}
	@computed get validations() {
		console.log('validations')
		return validate(this.schema, this.debouncedValues)
	}
```
