### ISSUE TITLE
Parametrized throttled computed

### ISSUE THREAD

**Issue by lishine** [danielearwicker/computed-async-mobx#32]
How it can be done ?

**Comment by danielearwicker** [comment]
Can you give an example of what you mean?

**Comment by lishine** [comment]
I want to throttle this, it depends on values observable:
```
	isRequired = computedFn((path: string) => {
		try {
			const { tests } = yup
				.reach(this.schema, path, this.values, this.values)
				.describe()
			return !!tests?.find((test: any) => test.name === 'required') ?? false
		} catch (error) {
			return false
		}
	})
```

It is actually another solution while Throttling observable does not work as in the other issue I created.
I wanted to throttle observable at first because I have two such functions that depend on values.

**Comment by danielearwicker** [comment]
Is this being called from an observer/reaction context, e.g. in a mobx UI where the rendering component(s) are observers?

**Comment by lishine** [comment]
Exactly

**Comment by danielearwicker** [comment]
Good, because that is essential for this stuff to work!

I guess it makes more sense to throttle the source data for this, so it sees them changing less frequently. Did you see my response on your other issue? I wrote a quick demo to show it working.

**Comment by lishine** [comment]
Yep, this is what I did.
Thank you!
