### ISSUE TITLE
Should depending on .busy keep autorun alive?

### ISSUE THREAD

**Issue by gkaemmer** [danielearwicker/computed-async-mobx#7]
One weird and common behavior that I've noticed is this (where `store.query` is a `computedAsync`):
```js
const Comp = observer(({ store }) => (
  store.query.busy
    ? <div>Loading...</div>
    : <div>Results are loaded: {query.value}</div>}
))
```

The problem is that `query.busy` gets set to true, and then the component technically stops observing `query.value`, so the autorun is cancelled and the promise is never resolved. An example fiddle is here: https://jsfiddle.net/qc26pb4k/6/.

A fix is simply to have the component explicitly depend on `query.value`, even while `query.busy` is true. See line 136 in the fiddle for an example of that fix.

Maybe depending on `busy` should automatically indicate that the component depends on `value`? Let me know your thoughts.

**Comment by danielearwicker** [comment]
Yes, definitely a bug. I am crazy busy for the next week or two, but then I have some vacation so will probably look at this then.

**Comment by gkaemmer** [comment]
If I have some time before then I'll fix these couple bugs and open a PR. Might require rethinking tests (as you pointed out in #6).

**Comment by danielearwicker** [comment]
I believe this is now fixed. The new 2.0.0 implementation is so simple, all the state properties are `computed`s that pull from a single internal computed.

**Comment by gkaemmer** [comment]
Yeah, just looked at the code and I think 2.0 fixes this issue. I appreciate the rewrite, looks great!
