### ISSUE TITLE
`busy` property temporarily returns `false`

### ISSUE THREAD

**Issue by DanielSWolf** [danielearwicker/computed-async-mobx#8]
I noticed that the `busy` property doesn't behave quite as I would have expected. It seems that when a `computedAsync` value gets initialized, `busy` returns `false`, then quickly switches to `true`. I would have expected it to return `true` from the beginning. As it stands, this behavior doesn't play nice with React (via `mobx-react`).

Consider this code:

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { computedAsync } from 'computed-async-mobx';
import delay from 'delay';
import { observer } from 'mobx-react';

async function timeConsumingOperation() {
  for (let i = 0; i < 5; i++) {
    await delay(500);
    console.log(`Waiting (${i})...`);
  }
}

@observer
class UseCase extends React.Component {
  observableValue = computedAsync({
    init: 'Initial dummy value',
    fetch: async () => {
      await timeConsumingOperation();
      return 'Computed value';
    },
  });

  render() {
    const { value, busy } = this.observableValue;
    console.log('render()', { value, busy });
    return (<ul>
      <li>value: {value}</li>
      <li>busy: {JSON.stringify(busy)}</li>
    </ul>);
  }
}

ReactDOM.render(
  <UseCase />,
  document.body.appendChild(document.createElement('div'))
);
```

This results in the following console output:

> render() Object {value: "Initial dummy value", busy: false}

> Warning: forceUpdate(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.

> render() Object {value: "Initial dummy value", busy: true}

> Waiting (0)...

> Waiting (1)...

> Waiting (2)...

> Waiting (3)...

> Waiting (4)...

> render() Object {value: "Computed value", busy: false}

It seems that this almost-instantaneous switch from `busy: false` to `busy: true` forces React to re-render the component before the first rendering is completely finished.

As a test, I introduced a computed helper property `busy` that is `true` if `observableValue.busy` is `true` *or* `observableValue.value` is the default value. This emulates the behavior I would have expected for `observableValue.busy`. With this hack in place, React doesn't print the warning.

**Comment by danielearwicker** [comment]
Interesting. I have just had an insanely busy couple of weeks but should have some time now to get into this. I want to rewrite the unit tests as well, as I remember they are horrible.

**Comment by danielearwicker** [comment]
Aaand some months later I've actually been able to do it. The new version 2.0.0 has a completely different implementation that happens to solve this problem. I've also turned the above into tests.

**Comment by DanielSWolf** [comment]
Works fine now. Thanks! 😃
