### ISSUE TITLE
delay not working in 2.0.0

### ISSUE THREAD

**Issue by jakubfalenczyk** [danielearwicker/computed-async-mobx#9]
Hey, I've noticed that after updating to 2.0.0 my `computed-async` with `delay` stopped working. I've run through the new code and I can see that the `delay` variable is not used anywhere. 

After going back to 1.2.0 everything works fine again.

**Comment by danielearwicker** [comment]
Oh man. Got so excited by the new simple implementation I didn’t notice that, also not tested for.

Please stay on 1.2 and I’ll post more to this issue ASAP.

**Comment by danielearwicker** [comment]
Apologies for the delay, I got struck down by a horrible virus (the biological kind).

I have restructured the library in 3.0.0 so it has a cleaner, simpler API and it now supports (and includes test for) the delay functionality. The old API is still there too but is harder to test so prefer the new one.

**Comment by jakubfalenczyk** [comment]
Great, thank you. I'll update to newest on monday. 
Hope you'll get better soon :)
